# Generated by Django 4.0.6 on 2022-07-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('task_text', models.CharField(max_length=200)),
            ],
        ),
    ]
