# Generated by Django 4.0.6 on 2022-07-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_task_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_text',
            new_name='task_title',
        ),
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.TextField(blank=True),
        ),
    ]
